spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/windowsense}
    username: ${SPRING_DATASOURCE_USERNAME:windowsense}
    password: ${SPRING_DATASOURCE_PASSWORD:windowsense}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  forward-headers-strategy: framework
